### ISSUE TITLE
enhancement: Support regular NVMe read/write (0x01, 0x02) in OCSSD 2.0 spec 

### ISSUE THREAD

**Issue by lovers-under-moon** [ucare-uchicago/FEMU#51]
![image](https://user-images.githubusercontent.com/45291298/115331377-5cf4a480-a1c8-11eb-96de-c487f10f59af.png)

FEMU OCSSD2.0 do not support  NVMe read/write (0x01, 0x02).

![image](https://user-images.githubusercontent.com/45291298/115331473-8c0b1600-a1c8-11eb-9d31-81be7e2033e5.png)

**Comment by huaicheng** [comment]
The regular NVMe READ/WRITE commands are not really meaningful for directly accessing an OC device (I might miss something). For the SPDK+OCSSD2.0 case, does the SPDK FTL soly rely on NVMe READ/WRITE to function? (no use of the VECTOR read/write/erase at all?)

SPDK might expect an "NVME_SUCCESS" or other types of return values instead of "NVME_DNR" for the regular read/write commands, or it might have issued the I/O and mgmt commands in an order that's not the same as LightNVM+kernel-NVMe driver, thus FEMU is not able to correctly handle it. 

PRs are welcome, otherwise, I work on this when I have time (timing not guaranteed).

**Comment by huaicheng** [comment]
Let me know if above patch works for you. Feel free to re-open the issue. I will mark it closed for now.
