### ISSUE TITLE
An improper locking due to the unreleased lock

### ISSUE THREAD

**Issue by ryancaicse** [ucare-uchicago/FEMU#62]
Hi developers, in the below codes, the lock `pthread_mutex_lock(&sem->lock);`  could be not released before program's exit `error_exit(rc, __func__);` . I think there is no harm to write `pthread_mutex_unlock(&sem->lock);`  before the `error_exit(rc, __func__);` for better resource management and code symmetry. Thanks!

https://github.com/ucare-uchicago/FEMU/blob/76a9d8e333f081a9df30b5f8706e9be81517665c/util/qemu-thread-posix.c#L320-L334

**Comment by ryancaicse** [comment]
Similarly,
https://github.com/ucare-uchicago/FEMU/blob/76a9d8e333f081a9df30b5f8706e9be81517665c/util/qemu-thread-posix.c#L280-L293

**Comment by ryancaicse** [comment]
https://github.com/ucare-uchicago/FEMU/blob/76a9d8e333f081a9df30b5f8706e9be81517665c/tools/virtiofsd/passthrough_ll.c#L3047-L3053

**Comment by ryancaicse** [comment]
https://github.com/ucare-uchicago/FEMU/blob/76a9d8e333f081a9df30b5f8706e9be81517665c/tools/virtiofsd/passthrough_ll.c#L3132-L3159

**Comment by huaicheng** [comment]
It seems to me that performing unlocking right before program exit() won't bring much value. Since the affected code segments are part of QEMU wrappers around posix (and are not directly used by FEMU so far), it's better to report the issue to the QEMU community. 

Thanks for opening this issue anyways!

**Comment by ryancaicse** [comment]
@huaicheng Thank you very much for your reply.
